name: Deploy Backend API

on:
  push:
    branches:
      - master  # This will trigger the workflow whenever you push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out the code in your repo

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3  # This will set up the SSH key
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the private key from GitHub Secrets

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install nodejs npm
          npm install  # Install necessary dependencies

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no vaishnavi@34.51.0.42 "cd /path/to/your/api && git pull && npm install && pm2 restart api"
          # This connects to your VM and restarts the app
